import Foundation
@testable import Autora

func listingFixture(
    id: String = "lst-x",
    sellerId: String = "s",
    make: String = "VW",
    model: String = "Passat",
    generation: String? = nil,
    year: Int = 2018,
    price: Int = 100,
    km: Int = 1,
    body: String = "седан",
    city: String = "Минск",
    isDemo: Bool = true,
    status: ListingStatus = .active,
    bumpedAt: TimeInterval = 1,
    vin: String? = nil,
    photoURLs: [String] = [],
    fuel: String = "бензин",
    isTop: Bool = false,
    bargaining: Bool = false,
    customsCleared: Bool = true
) -> Listing {
    Listing(
        id: id,
        sellerId: sellerId,
        sellerName: "S",
        sellerPhone: "+375291000000",
        sellerListingCount: 1,
        make: make,
        model: model,
        generation: generation,
        year: year,
        priceBYN: price,
        mileageKm: km,
        body: body,
        fuel: fuel,
        transmission: "автомат",
        drivetrain: "передний",
        engineLiters: 2.0,
        powerHp: 150,
        city: city,
        region: "Минская",
        condition: .used,
        registered: true,
        customsCleared: customsCleared,
        wheel: .left,
        hasPhotos: !photoURLs.isEmpty,
        bargaining: bargaining,
        exchange: false,
        forParts: false,
        damaged: false,
        vin: vin,
        isTop: isTop,
        isDemo: isDemo,
        status: status,
        photoURLs: photoURLs,
        description: "",
        views: 0,
        favoritesCount: 0,
        phoneReveals: 0,
        bumpedAt: bumpedAt,
        createdAt: bumpedAt
    )
}
